# Generated by Django 4.0.3 on 2022-06-23 12:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_name', models.CharField(max_length=156, verbose_name='torto pavadinimas')),
                ('description', models.TextField(default='Aprašymas ruošiamas', max_length=1000, verbose_name='trumas aprašymas')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='kaina')),
            ],
            options={
                'verbose_name': 'tortas',
                'verbose_name_plural': 'tortai',
                'ordering': ['cake_name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='vardas')),
                ('last_name', models.CharField(max_length=100, verbose_name='pavardė')),
                ('email_name', models.EmailField(default='@', max_length=250, verbose_name='el.paštas')),
                ('phone_number', models.PositiveIntegerField(verbose_name='nr')),
            ],
            options={
                'verbose_name': 'duomenys apie klientą',
                'verbose_name_plural': 'duomenys apie klientus',
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='progos pavadinimas')),
            ],
            options={
                'verbose_name': 'proga',
                'verbose_name_plural': 'progos',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='užsakymo numeris')),
                ('deadline', models.DateField(blank=True, db_index=True, verbose_name='pagaminti datai: ')),
                ('notice', models.CharField(default='', max_length=500, null=True, verbose_name='pastabos')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Užsakymo suma: ')),
                ('status', models.CharField(blank=True, choices=[('p', 'patvirtintas'), ('g', 'gaminamas'), ('a', 'paruoštas atsiemimui')], db_index=True, default='p', max_length=1, verbose_name='užsakymo būsena')),
                ('cake', models.ManyToManyField(related_name='orders', to='tortukai.cake', verbose_name='tortas')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tortukai.client', verbose_name='klientas')),
            ],
            options={
                'verbose_name': 'užakymą',
                'verbose_name_plural': 'užsakymai',
                'ordering': ['deadline'],
            },
        ),
        migrations.AddField(
            model_name='cake',
            name='occasion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cakes', to='tortukai.occasion', verbose_name='tinka progai'),
        ),
    ]
