# Generated by Django 4.0.3 on 2022-06-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tortukai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='vardas')),
                ('last_name', models.CharField(max_length=100, verbose_name='pavardė')),
                ('email_name', models.EmailField(max_length=250)),
                ('phone_number', models.IntegerField(default=370, max_length=11)),
            ],
            options={
                'verbose_name': 'duomenys apie klientą',
                'verbose_name_plural': 'duomenys apie klientus',
                'ordering': ['first_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='occasion',
            options={'ordering': ['title'], 'verbose_name': 'proga', 'verbose_name_plural': 'progos'},
        ),
        migrations.AlterField(
            model_name='occasion',
            name='title',
            field=models.CharField(max_length=100, verbose_name='progos pavadinimas'),
        ),
    ]
