# Generated by Django 4.0.3 on 2022-06-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tortukai', '0003_cake_alter_client_email_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['deadline'], 'verbose_name': 'užakymas', 'verbose_name_plural': 'užsakymai'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'užsakymas patvirtintas'), ('g', 'užsakymas gaminamas'), ('a', 'užsakymas paruoštas atsiemimui')], db_index=True, default='p', max_length=1, verbose_name='užsakymo būsena'),
        ),
    ]
