# Generated by Django 4.0.3 on 2022-06-25 08:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tortukai', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='description',
            field=tinymce.models.HTMLField(default='Aprašymas ruošiamas', verbose_name='trumas aprašymas'),
        ),
    ]
