# Generated by Django 4.0.3 on 2022-06-26 14:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tortukai', '0005_alter_cake_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='Aprašymas ruošiamas', null=True, verbose_name='trumas aprašymas'),
        ),
    ]
