# Generated by Django 4.0.3 on 2022-06-26 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tortukai', '0007_cakereview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cakereview',
            options={'verbose_name': 'kliento atsiliepimas', 'verbose_name_plural': 'klientų atsiliepimai'},
        ),
    ]
