# Generated by Django 4.0.3 on 2022-06-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tortukai', '0007_alter_client_email_name_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(default='+370', max_length=20, verbose_name='tel.nr.:'),
        ),
    ]
