# Generated by Django 4.0.4 on 2022-06-27 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tortukai', '0008_alter_cakereview_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cakereview',
            options={'ordering': ['created_at'], 'verbose_name': 'kliento atsiliepimas', 'verbose_name_plural': 'klientų atsiliepimai'},
        ),
    ]
