# Generated by Django 4.0.3 on 2022-06-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tortukai', '0008_alter_client_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='kaina'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.PositiveIntegerField(verbose_name='nr'),
        ),
    ]
