# Generated by Django 4.0.4 on 2022-06-27 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tortukai', '0009_alter_cakereview_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='client',
            new_name='old_client',
        ),
    ]
