# Generated by Django 4.0.4 on 2022-06-27 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tortukai', '0010_rename_client_order_old_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cakereview',
            old_name='client',
            new_name='subscriber',
        ),
    ]
