# Generated by Django 4.0.4 on 2022-06-27 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tortukai', '0011_rename_client_cakereview_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='old_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tortukai.client', verbose_name='pirkėjas'),
        ),
    ]
