# Generated by Django 4.0.4 on 2022-06-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tortukai', '0012_alter_order_old_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='old_client',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
