# Generated by Django 4.0.4 on 2022-06-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tortukai', '0013_remove_order_old_client_delete_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='description',
            field=models.TextField(blank=True, default='Aprašymas ruošiamas', max_length=1000, null=True, verbose_name='trumas aprašymas'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notice',
            field=models.TextField(default='', max_length=500, null=True, verbose_name='pastabos'),
        ),
    ]
