# Generated by Django 4.0.4 on 2022-06-28 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tortukai', '0014_alter_cake_description_alter_order_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notice',
            field=models.CharField(default='-', max_length=300, null=True, verbose_name='pastabos'),
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='kiekis')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kaina už vnt.')),
                ('line_created', models.DateTimeField(auto_now_add=True)),
                ('remark', models.CharField(default='-', max_length=300, null=True, verbose_name='pastabos')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to=settings.AUTH_USER_MODEL, verbose_name='užsakymas')),
            ],
            options={
                'verbose_name': 'užsakymo eilutė',
                'verbose_name_plural': 'užsakymų eilutės',
            },
        ),
    ]
