# Generated by Django 4.0.4 on 2022-06-28 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tortukai', '0017_remove_order_cake_orderline_cake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='cake',
        ),
        migrations.AddField(
            model_name='orderline',
            name='cake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='tortukai.cake', verbose_name='torto pav.'),
        ),
    ]
