# Generated by Django 4.0.4 on 2022-06-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tortukai', '0019_cake_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderline',
            old_name='price',
            new_name='price_per_item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='order_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Užsakymo suma: '),
        ),
        migrations.AddField(
            model_name='orderline',
            name='summ_per_line',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Suma'),
        ),
    ]
