# Generated by Django 4.0.4 on 2022-06-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tortukai', '0020_rename_price_orderline_price_per_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='nuolaida užsakymui'),
        ),
    ]
