# Generated by Django 4.0.4 on 2022-06-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tortukai', '0022_alter_orderline_price_per_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='nuolaida užsakymui, proc.'),
        ),
    ]
