# Generated by Django 4.0.4 on 2022-06-28 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tortukai', '0024_alter_orderline_price_per_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='cake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='tortukai.cake', verbose_name='tortukas'),
        ),
    ]
