# Generated by Django 4.0.4 on 2022-06-29 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tortukai', '0025_alter_orderline_cake'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderline',
            options={'ordering': ['order'], 'verbose_name': 'užsakymo eilutė', 'verbose_name_plural': 'užsakymų eilutės'},
        ),
    ]
