# Generated by Django 4.0.4 on 2022-06-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tortukai', '0026_alter_orderline_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'patvirtintas'), ('g', 'gaminamas'), ('a', 'paruoštas atsiemimui'), ('u', 'uždarytas/atšauktas')], db_index=True, default='p', max_length=1, verbose_name='užsakymo būsena'),
        ),
    ]
