# Generated by Django 4.0.3 on 2022-06-29 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tortukai', '0028_alter_order_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='tortukai.order', verbose_name='užsakymas'),
        ),
    ]
