# Generated by Django 4.0.3 on 2022-06-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tortukai', '0029_alter_orderline_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='price_per_item',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Kaina už vnt.'),
        ),
    ]
